# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.9.5.dev3+g5d0c379.d20230918'
__version_tuple__ = version_tuple = (0, 9, 5, 'dev3', 'g5d0c379.d20230918')
